services:
  obf:
    image: mkrlenron/lenron-obf:0.1
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: .
        target: /usr/local/apache2/htdocs
      - type: bind
        source: ./obf
        target: /usr/local/apache2/htdocs/obf
      - type: bind
        source: /tmp/mysqld
        target: /run/mysqld
    depends_on:
      - dbase

  dbase:
    image: mariadb:12.0.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pwd
      MARIADB_USER: chatriwe_admin
      MARIADB_PASSWORD: Vuu_fQY1#qH,
      MARIADB_DATABASE: chatriwe_obf
      #MARIADB_TCP_PORT: 3306
    volumes:
      - ./obf.sql:/docker-entrypoint-initdb.d/obf.sql
      - mariadb_data:/var/lib/mysql
      - /tmp/mysqld:/var/run/mysqld

volumes:
  mariadb_data:
